# Generated by Django 5.2.5 on 2026-08-31 03:31

import django.db.models.deletion
import interests.models
import topics.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topics', '0003_remove_topic_approval'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestEntity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registry_id', models.CharField(default=interests.models.new_registry_id, max_length=16, unique=True)),
                ('canonical_name', models.CharField(max_length=80, unique=True)),
                ('normalized_name', models.CharField(editable=False, max_length=80, unique=True)),
                ('entity_type', models.CharField(choices=[('作品', '作品'), ('角色', '角色'), ('游戏', '游戏'), ('玩具/品牌', '玩具/品牌'), ('创作者/账号', '创作者/账号'), ('网络热梗', '网络热梗'), ('其他', '其他')], max_length=32)),
                ('broad_topic', models.CharField(choices=[('影视动漫与角色', '影视动漫与角色'), ('电子游戏与互动玩法', '电子游戏与互动玩法'), ('故事绘本与文学', '故事绘本与文学'), ('音乐儿歌与音频', '音乐儿歌与音频'), ('学习语言与数学', '学习语言与数学'), ('科学自然与百科', '科学自然与百科'), ('动物植物与宠物', '动物植物与宠物'), ('家庭校园与人际', '家庭校园与人际'), ('情绪陪伴与自我表达', '情绪陪伴与自我表达'), ('日常生活与饮食健康', '日常生活与饮食健康'), ('设备与产品使用', '设备与产品使用'), ('其他明确内容', '其他明确内容')], max_length=40)),
                ('status', models.CharField(choices=[('approved', '已批准'), ('merged', '已合并')], default='approved', max_length=16)),
                ('registry_order', models.PositiveIntegerField(default=100000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merge_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merged_entities', to='interests.interestentity')),
            ],
            options={
                'ordering': ['registry_order', 'registry_id'],
            },
        ),
        migrations.CreateModel(
            name='InterestCandidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_date', models.DateField()),
                ('phrase', models.CharField(max_length=80)),
                ('normalized_phrase', models.CharField(max_length=80)),
                ('query_count', models.PositiveIntegerField()),
                ('users', models.PositiveIntegerField()),
                ('sessions', models.PositiveIntegerField()),
                ('seven_day_growth', models.FloatField(blank=True, null=True)),
                ('suggested_name', models.CharField(blank=True, max_length=80)),
                ('suggested_type', models.CharField(blank=True, max_length=32)),
                ('suggested_aliases', models.JSONField(blank=True, default=list)),
                ('model_confidence', models.CharField(blank=True, max_length=16)),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已批准'), ('merged', '已合并'), ('rejected', '已拒绝')], default='pending', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_candidates', to='topics.topicjob')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interest_reviews', to=settings.AUTH_USER_MODEL)),
                ('resolved_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_candidates', to='interests.interestentity')),
            ],
            options={
                'ordering': ['-data_date', '-users', '-sessions', 'normalized_phrase'],
            },
        ),
        migrations.CreateModel(
            name='InterestBackfillRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', '待处理'), ('running', '处理中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='backfill_requests', to='interests.interestentity')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterestAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=80)),
                ('normalized', models.CharField(editable=False, max_length=80, unique=True)),
                ('ambiguous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='interests.interestentity')),
            ],
            options={
                'ordering': ['-ambiguous', 'normalized'],
            },
        ),
        migrations.CreateModel(
            name='InterestRegistrySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registry_version', models.CharField(max_length=32)),
                ('sha256', models.CharField(max_length=64)),
                ('relative_path', models.CharField(max_length=500, validators=[topics.models.validate_relative_path])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interest_registry_snapshot', to='topics.topicjob')),
            ],
        ),
        migrations.CreateModel(
            name='InterestReviewEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=32)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_events', to='interests.interestcandidate')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterestSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_date', models.DateField(unique=True)),
                ('schema_version', models.CharField(max_length=64)),
                ('engine_version', models.CharField(max_length=64)),
                ('source_sha256', models.CharField(max_length=64)),
                ('registry_sha256', models.CharField(max_length=64)),
                ('workbook_sha256', models.CharField(max_length=64)),
                ('payload', models.JSONField()),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='interest_snapshot', to='topics.topicjob')),
            ],
            options={
                'ordering': ['data_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='interestcandidate',
            constraint=models.UniqueConstraint(fields=('job', 'normalized_phrase'), name='unique_interest_candidate_per_job'),
        ),
    ]
