# Generated by Django 5.2.5 on 2026-08-31 09:38

import django.db.models.deletion
import interest_engine.registry
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestcandidate',
            name='suggested_parent_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='interestcandidate',
            name='suggested_subtype',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='interestentity',
            name='entity_subtype',
            field=models.CharField(choices=[('动画', '动画'), ('特摄', '特摄'), ('电影', '电影'), ('电视剧', '电视剧'), ('文学绘本', '文学绘本'), ('音乐音频', '音乐音频'), ('手游', '手游'), ('端游', '端游'), ('主机游戏', '主机游戏'), ('沙盒 UGC', '沙盒 UGC'), ('作品角色', '作品角色'), ('角色组合', '角色组合'), ('潮玩', '潮玩'), ('玩具', '玩具'), ('主播', '主播'), ('短视频账号', '短视频账号'), ('影视台词梗', '影视台词梗'), ('游戏语音梗', '游戏语音梗'), ('主播切片', '主播切片'), ('空耳音频', '空耳音频'), ('网络句式', '网络句式'), ('抽象食品', '抽象食品'), ('低俗黑话', '低俗黑话'), ('歧视性用语', '歧视性用语'), ('风险事件', '风险事件'), ('其他热梗', '其他热梗')], default=interest_engine.registry.EntitySubtype['OTHER_MEME'], max_length=32),
        ),
        migrations.AddField(
            model_name='interestentity',
            name='match_rules',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='interestentity',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interest_children', to='interests.interestentity'),
        ),
        migrations.AddField(
            model_name='interestentity',
            name='safety_category',
            field=models.CharField(choices=[('none', 'none'), ('sexual_content', 'sexual_content'), ('discrimination', 'discrimination'), ('real_case', 'real_case'), ('eating_disorder', 'eating_disorder'), ('insult', 'insult')], default=interest_engine.registry.SafetyCategory['NONE'], max_length=32),
        ),
        migrations.AddField(
            model_name='interestentity',
            name='source_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='interestentity',
            name='source_platform',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='interestentity',
            name='visibility',
            field=models.CharField(choices=[('public', 'public'), ('restricted', 'restricted')], default=interest_engine.registry.Visibility['PUBLIC'], max_length=16),
        ),
    ]
