# Generated by Django 5.2.5 on 2026-09-07 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0005_interestdailycontribution'),
        ('topics', '0007_product_version_partition'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='interestsegmentsnapshot',
            name='unique_interest_segment_per_date_dimension',
        ),
        migrations.AddField(
            model_name='interestbackfillrequest',
            name='product_version',
            field=models.CharField(choices=[('M1', 'M1'), ('M2', 'M2')], default='M1', max_length=2),
        ),
        migrations.AddField(
            model_name='interestdailycontribution',
            name='product_version',
            field=models.CharField(choices=[('M1', 'M1'), ('M2', 'M2')], default='M1', max_length=2),
        ),
        migrations.AddField(
            model_name='interestsegmentsnapshot',
            name='product_version',
            field=models.CharField(choices=[('M1', 'M1'), ('M2', 'M2')], default='M1', max_length=2),
        ),
        migrations.AddField(
            model_name='interestsnapshot',
            name='product_version',
            field=models.CharField(choices=[('M1', 'M1'), ('M2', 'M2')], default='M1', max_length=2),
        ),
        migrations.AlterField(
            model_name='interestdailycontribution',
            name='data_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='interestsnapshot',
            name='data_date',
            field=models.DateField(),
        ),
        migrations.AddConstraint(
            model_name='interestdailycontribution',
            constraint=models.UniqueConstraint(fields=('product_version', 'data_date'), name='unique_interest_contribution_version_date'),
        ),
        migrations.AddConstraint(
            model_name='interestsegmentsnapshot',
            constraint=models.UniqueConstraint(fields=('product_version', 'data_date', 'dimension_set'), name='unique_interest_segment_version_date_dim'),
        ),
        migrations.AddConstraint(
            model_name='interestsnapshot',
            constraint=models.UniqueConstraint(fields=('product_version', 'data_date'), name='unique_interest_snapshot_version_date'),
        ),
    ]
