# Generated by Django 5.2.5 on 2026-08-20 07:56

import django.db.models.deletion
import topics.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_date', models.DateField()),
                ('original_name', models.CharField(max_length=255)),
                ('expected_size', models.BigIntegerField()),
                ('received_size', models.BigIntegerField(default=0)),
                ('expected_sha256', models.CharField(blank=True, max_length=64)),
                ('input_sha256', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('uploading', '上传中'), ('validating', '本地校验'), ('base_running', '基础分析'), ('base_verifying', '基础验证'), ('awaiting_approval', '等待语义确认'), ('queued', '排队'), ('semantic_running', '语义分析'), ('final_verifying', '最终验证'), ('publishing', '发布'), ('completed', '发布完成'), ('waiting_model', '等待模型'), ('failed', '失败'), ('expired', '已过期')], default='uploading', max_length=32)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('preflight', models.JSONField(blank=True, default=dict)),
                ('approval_fingerprint', models.CharField(blank=True, max_length=64)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_message', models.CharField(blank=True, max_length=240)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('expires_at', models.DateTimeField(default=topics.models.default_expiry)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_topic_jobs', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topic_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TopicAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='topic_audit_events', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='topics.topicjob')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TopicArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('topic_workbook', '话题报告'), ('topic_detail', '隐私安全明细'), ('topic_detail_zip', '明细压缩包')], max_length=32)),
                ('relative_path', models.CharField(max_length=500, validators=[topics.models.validate_relative_path])),
                ('download_name', models.CharField(max_length=255)),
                ('sha256', models.CharField(max_length=64)),
                ('byte_size', models.BigIntegerField()),
                ('verified', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(default=topics.models.default_expiry)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='topics.topicjob')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TopicSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_date', models.DateField(unique=True)),
                ('taxonomy_version', models.CharField(max_length=32)),
                ('catalog_revision', models.CharField(max_length=32)),
                ('report_schema', models.CharField(max_length=64)),
                ('source_sha256', models.CharField(max_length=64)),
                ('workbook_sha256', models.CharField(max_length=64)),
                ('payload', models.JSONField()),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='snapshot', to='topics.topicjob')),
            ],
            options={
                'ordering': ['data_date'],
            },
        ),
        migrations.AddIndex(
            model_name='topicjob',
            index=models.Index(fields=['status', 'created_at'], name='topics_topi_status_b4feb2_idx'),
        ),
        migrations.AddIndex(
            model_name='topicjob',
            index=models.Index(fields=['data_date'], name='topics_topi_data_da_abe476_idx'),
        ),
    ]
