# Generated by Django 5.2.5 on 2026-08-20 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicjob',
            name='next_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topicjob',
            name='runtime_state',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
