# Generated by Django 5.2.5 on 2026-08-31 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_remove_topic_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicjob',
            name='pipeline',
            field=models.CharField(choices=[('legacy_topic', '旧话题分析'), ('interest_v1', 'IP兴趣分析 v1')], default='legacy_topic', max_length=24),
        ),
        migrations.AlterField(
            model_name='topicartifact',
            name='kind',
            field=models.CharField(choices=[('topic_workbook', '话题报告'), ('topic_detail', '隐私安全明细'), ('topic_detail_zip', '明细压缩包'), ('interest_workbook', 'IP兴趣报告'), ('interest_detail_zip', '兴趣隐私安全明细')], max_length=32),
        ),
        migrations.AlterField(
            model_name='topicjob',
            name='status',
            field=models.CharField(choices=[('uploading', '上传中'), ('validating', '本地校验'), ('base_running', '基础分析'), ('base_verifying', '基础验证'), ('queued', '排队'), ('semantic_running', '语义分析'), ('interest_running', '本地兴趣分析'), ('interest_verifying', '兴趣结果验证'), ('final_verifying', '最终验证'), ('publishing', '发布'), ('completed', '发布完成'), ('waiting_model', '等待模型'), ('failed', '失败'), ('expired', '已过期')], default='uploading', max_length=32),
        ),
    ]
