# Generated by Django 5.2.5 on 2026-08-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0004_topicjob_pipeline_alter_topicartifact_kind_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topicjob",
            name="pipeline",
            field=models.CharField(
                choices=[
                    ("legacy_topic", "旧话题分析"),
                    ("shadow", "兴趣与旧话题影子双跑"),
                    ("interest_v1", "IP兴趣分析 v1"),
                ],
                default="legacy_topic",
                max_length=24,
            ),
        ),
    ]
