# Generated by Django 5.2.5 on 2026-09-07 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0006_interest_only_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicjob',
            name='product_version',
            field=models.CharField(choices=[('M1', 'M1'), ('M2', 'M2')], default='M1', max_length=2),
        ),
    ]
